# 1. Import necessary libraries

In [36]:
import pandas as pd
import numpy as np
import keras
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

# 2. Import dataset

In [3]:
Diabetes_dataset = pd.read_csv("diabetes.csv")
Diabetes_dataset

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1


# 3.Data understanding

In [4]:
Diabetes_dataset.shape

(768, 9)

In [5]:
Diabetes_dataset.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
Diabetes_dataset.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

# 4.Data preprocessing

In [7]:
X = Diabetes_dataset.drop('Outcome', axis=1)
y = Diabetes_dataset['Outcome']

In [8]:
X.shape, y.shape

((768, 8), (768,))

# 5. Model Building

In [10]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [12]:
model = Sequential()
model.add(Dense(12, input_dim=8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))

C:\Users\varun\anaconda3\envs\Tensor_flow\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
model.compile(optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy'])

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=12,shuffle=True,stratify=y)

In [18]:
X_train.shape, y_train.shape

((614, 8), (614,))

In [20]:
X_test.shape, y_test.shape

((154, 8), (154,))

In [22]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 6.Model trainig | testing | evaluation

In [23]:
model.fit(x=X_train,y=y_train,batch_size=16,epochs=50,validation_split=0.20)

Epoch 1/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.6497 - loss: 0.6909 - val_accuracy: 0.6992 - val_loss: 0.6865
Epoch 2/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6395 - loss: 0.6833 - val_accuracy: 0.6992 - val_loss: 0.6698
Epoch 3/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6395 - loss: 0.6596 - val_accuracy: 0.7073 - val_loss: 0.6320
Epoch 4/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6802 - loss: 0.6115 - val_accuracy: 0.7236 - val_loss: 0.5766
Epoch 5/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7373 - loss: 0.5582 - val_accuracy: 0.7480 - val_loss: 0.5373
Epoch 6/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7862 - loss: 0.5159 - val_accuracy: 0.7317 - val_loss: 0.5280
Epoch 7/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7923 - loss: 0.4907 - val_accuracy: 0.7236 - val_loss: 0.5294
Epoch 8/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7902 - loss: 0.4743 - val_accuracy: 0.7236 - val_loss

# 9.Model prediction

In [25]:
y_pred = model.predict(X_test) 
y_pred = (y_pred > 0.6).astype(int)
y_pred

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step 


array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [26]:
from sklearn.metrics import classification_report, confusion_matrix

In [28]:
print(classification_report(y_test,
    y_pred))

              precision    recall  f1-score   support

           0       0.79      0.86      0.82       100
           1       0.69      0.57      0.63        54

    accuracy                           0.76       154
   macro avg       0.74      0.72      0.72       154
weighted avg       0.75      0.76      0.75       154



In [29]:
print(confusion_matrix(y_test, y_pred))

[[86 14]
 [23 31]]


# 10.New input prediction

In [31]:
model.save("diabetes_intel.h5")

In [32]:
from keras.models import load_model
diab_model = load_model("diabetes_intel.h5")

In [33]:
import numpy as np
new_data = np.array([[6,148,72,35,0,33.6, 0.627,50]])
new_data = scaler.transform(new_data)
probablity = diab_model.predict(new_data)
print("probablity:", probablity)
final_class = (probablity > 0.6).astype(int)
final_class

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
probablity: [[0.64138985]]


C:\Users\varun\anaconda3\envs\Tensor_flow\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[1]])