# why Numpy?

## Because they reveal 5 core important purposes
1. speed
2. structure
3. vectorization
4. math
5. AI Foundation

   ==================================================================================


## numpy arrays

In [11]:
cost = [30, 35, 32]
cost

[30, 35, 32]

In [12]:
type(cost)

list

In [13]:
import numpy as np

In [15]:
np.array(object = [30, 35, 32.4])

array([30. , 35. , 32.4])

### np.array creates an array in numpy - when numbers are stored in array math calculations are faster and easier in large scale datasets

In [17]:
a = [2,3,4]
b = [3,4,5]
a_1 = np.array(object = a)
b_1 = np.array(object=b)
print(a+b)
print(a_1+b_1)

[2, 3, 4, 3, 4, 5]
[5 7 9]


### 1. speed
python list - loop based - slow

numpy array - c-level execution - optimized

In [20]:
import numpy as np
import time

size = 100000

list1 = list(range(size))
list2 = list(range(size))

arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
list_time = time.time() - start

start_time = time.time()
result_arr = arr1 + arr2
array_time = time.time() - start_time

print(f"list time : {list_time:.5f} seconds")
print(f"numpy time : {array_time:.5f} seconds")
print(f"time difference {list_time/array_time:.2f}x faster")

list time : 0.03064 seconds
numpy time : 0.00073 seconds
time difference 41.71x faster


### 2. Multi dimensional data handling (data structures) - to handle 2D(black and white) and 3D(color) images

In [27]:
arr_demo = np.array([1,2,3])
arr_demo.ndim

1

In [28]:
arr_demo.shape

(3,)

In [57]:
arr = np.array([[[1,3,2],[3,4,5]],[[2,3,4],[4,5,6]]])

In [58]:
arr.ndim

3

In [ ]:
arr.shape

In [45]:
arr[0][1][1]

np.int64(5)

### 3. vectorization - removes repetition and execute parallelly, 
Loop - sequential

vectorization - parallel execution

### 4. Mathematical and stastistical operations

#### mean, variance and std.deviation - basics of ML
     LINEAR ALGEBRA - core of DL - Back propogation uses linear algebra

### 5. foundation of ML and AI

In [ ]:
np.dot()

##### ======================================================================

# build a simple brain using Numpy

## Problem statement

In [ ]:
y = 2x + 3

## Import  necessary libraries

In [60]:
import numpy as np

## data collection

In [61]:
X = np.array([[1],[2],[3],[4]])  # input
y = np.array([[5],[7],[9],[11]])   # actual output

## Data understanding

In [63]:
X,y

(array([[1],
        [2],
        [3],
        [4]]),
 array([[ 5],
        [ 7],
        [ 9],
        [11]]))

In [65]:
X.shape, y.shape

((4, 1), (4, 1))

In [67]:
X.ndim, y.ndim

(2, 2)

## data preparation, model building, model training

### phase 1-------- core 4 step setup stage 

####  4.1 Initialize weights randomly

In [99]:
w = np.random.randn(1,1)
b = np.random.randn(1,1)

print("Initial weight : ", w)
print("Initial Bias : ", b)

Initial weight :  [[1.12585389]]
Initial Bias :  [[-0.06875178]]


#### 4.2 Forward pass prediction

In [100]:
def forward(X, w, b):
    return np.dot(X, w) + b
y_pred = forward(X, w, b)
print("Predictions: \n", y_pred)

Predictions: 
 [[1.05710211]
 [2.18295601]
 [3.3088099 ]
 [4.43466379]]


#### 4.3 loss function

In [101]:
def loss(y, y_pred):
    return np.mean((y-y_pred) ** 2)
print("Loss:", loss(y,y_pred))

Loss: 28.560910230867755


#### 4.4 backward propagation (manual gradient)

In [102]:
def gradients(X, y, y_pred):
    n = len(X)

    dw = (-2/n) * np.dot(X.T, (y-y_pred))
    db = (-2/n) * np.sum(y - y_pred)

    return dw, db


### phase 2 - the actual training phase

In [103]:
print("Before Training:", forward(np.array([[5]]), w, b))

Before Training: [[5.56051768]]


In [104]:
learning_rate = 0.01

for i in range(1000):
    y_pred = forward(X, w, b)

    dw, db = gradients(X, y, y_pred)

    w = w - learning_rate * dw
    b = b - learning_rate * db

    if i % 100 == 0:
        print(f"Epoch {i}, loss: {loss(y, y_pred)}")

Epoch 0, loss: 28.560910230867755
Epoch 100, loss: 0.5657692041548893
Epoch 200, loss: 0.3106005113362499
Epoch 300, loss: 0.17051595762700653
Epoch 400, loss: 0.09361121680182496
Epoch 500, loss: 0.051391435928166154
Epoch 600, loss: 0.028213282307289814
Epoch 700, loss: 0.015488753800603232
Epoch 800, loss: 0.008503140176416703
Epoch 900, loss: 0.004668122031675368


In [105]:
print("After training:", forward(np.array([[5]]), w, b))

After training: [[13.08678696]]


### so learning = updating weight and bias to reduce error

## step 5 result

In [107]:
print("Final w:", w)
print("Final b:", b)

Final w: [[2.04213208]]
Final b: [[2.87612653]]
