# 1. List vs Array properties

1. In list we cannot do element-wise operation, but in arrays we can.
2. List to array conversion is possible, Array to list conversion is also possible, but we will lose dimensions.
3. List can hold heterogeneous datatype, but Numpy array is a homogenenuos datatype

## 1.1 Create 1D array

In [4]:
import numpy as np

In [2]:
arr_1 = np.array([1,2,5,3,10,9,6])

print("Array : ",             arr_1)
print("Type :",               type(arr_1))
print("No. of Dimensions :", arr_1.ndim)
print("No. of elements :", arr_1.size)
print("Index of maximum number :", arr_1.argmax()) # argmax is an important function used in softmax - to provide weightage to nueron

Array :  [ 1  2  5  3 10  9  6]
Type : <class 'numpy.ndarray'>
No. of Dimensions : 1
No. of elements : 7
Index of maximum number : 4


In [9]:
arr_2 = np.array([1,2,3,46,7,9])

In [12]:
arr_2.fill(7)
print(arr_2)
print("No. of elements :", arr_2.size)

[7 7 7 7 7 7]
No. of elements : 6


In [13]:
arr_3 = arr_2.repeat(repeats=20)
print(arr_3)
print("No. of elements :", arr_3.size)

[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7]
No. of elements : 120


In [15]:
arr_2 = np.array([1,2,3,46,7,9])
arr_2 + 2

array([ 3,  4,  5, 48,  9, 11])

In [16]:
arr_2 * 2

array([ 2,  4,  6, 92, 14, 18])

## 1.2 Create list and understand the differences

In [1]:
list1 = [2,4,7,9,12]
list1

[2, 4, 7, 9, 12]

In [2]:
list1 + 2

TypeError: can only concatenate list (not "int") to list

In [21]:
list1.append([56])
list1

[2, 4, 7, 9, 12, [5, 6], 7, 8, [56]]

In [22]:
list1.extend([78])
list1

[2, 4, 7, 9, 12, [5, 6], 7, 8, [56], 78]

In [24]:
list_1 = ['a','b']
list_1

['a', 'b']

In [26]:
list_1.append(['cd'])
list_1

['a', 'b', ['cd']]

In [27]:
list_1.extend(['cd'])
list_1

['a', 'b', ['cd'], 'cd']

## 1.3 create 2D array

In [5]:
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2)
print("Number of dimensions :", arr_2.ndim)

[[1 2 3]
 [4 5 6]]
Number of dimensions : 2


In [6]:
arr_21 = np.array([[1,2,3]])
print(arr_21)
print("Number of dimensions :", arr_21.ndim)

[[1 2 3]]
Number of dimensions : 2


In [9]:
arr_23 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_23)
print("Number of dimensions :", arr_23.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of dimensions : 2


## 1.4 Create a 3D array

In [8]:
arr_3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3)
print("Number of dimensions :", arr_3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Number of dimensions : 3


In [11]:
arr_31 = np.array([[[1,2]]])
print(arr_31)
print("Number of dimensions :", arr_31.ndim)

[[[1 2]]]
Number of dimensions : 3


In [15]:
arr_32 = np.array([[[2,3],[1,2]],[[7,8],[5,6]]])
print(arr_32)
print("Number of dimensions :", arr_32.ndim)

[[[2 3]
  [1 2]]

 [[7 8]
  [5 6]]]
Number of dimensions : 3


## 1.5 convert int to float

In [17]:
arr_3_float = arr_3.astype('float')
arr_3_float

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

In [18]:
arr_3_float.dtype

dtype('float64')

## 1.6 List to array conversion

In [19]:
list_2 = [[1,2,3],[4,5,6]]
type(list_2)

list

In [20]:
list_2_arr = np.array(list_2)
list_2_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
print(type(list_2_arr))
print(list_2_arr.ndim)

<class 'numpy.ndarray'>
2


## 1.7 Array to list conversion

In [23]:
arr_2_list = list_2_arr.tolist()
arr_2_list

[[1, 2, 3], [4, 5, 6]]

In [24]:
type(arr_2_list)

list

# 2. Reshaping advantage using Numpy

### 2.1 Reshape using Numpy

In [26]:
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2)
print("Number of dimensions :", arr_2.ndim)
print("Number of dimensions :", arr_2.shape)

[[1 2 3]
 [4 5 6]]
Number of dimensions : 2
Number of dimensions : (2, 3)


In [27]:
arr_2r = arr_2.reshape(3,2)
print(arr_2r)
print("Number of dimensions :", arr_2r.ndim)
print("Number of dimensions :", arr_2r.shape)

[[1 2]
 [3 4]
 [5 6]]
Number of dimensions : 2
Number of dimensions : (3, 2)


In [28]:
arr_2r1 = arr_2r.reshape(1,6)
print(arr_2r1)
print("Number of dimensions :", arr_2r1.ndim)
print("Number of dimensions :", arr_2r1.shape)

[[1 2 3 4 5 6]]
Number of dimensions : 2
Number of dimensions : (1, 6)


In [29]:
arr_2rr = arr_2r1.reshape(6,1)
print(arr_2rr)
print("Number of dimensions :", arr_2rr.ndim)
print("Number of dimensions :", arr_2rr.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Number of dimensions : 2
Number of dimensions : (6, 1)


### 2.2 Convert n-dimension to 1 dimension

In [30]:
arr_3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3)
print("Number of dimensions :", arr_3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Number of dimensions : 3


In [31]:
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2)
print("Number of dimensions :", arr_2.ndim)

[[1 2 3]
 [4 5 6]]
Number of dimensions : 2


In [33]:
nd_1d_array = arr_3.flatten()
print(nd_1d_array)
print(nd_1d_array.ndim)

[1 2 3 4 5 6 7 8 9]
1


In [34]:
n2d_1d_array = arr_2.flatten()
print(n2d_1d_array)
print(n2d_1d_array.ndim)

[1 2 3 4 5 6]
1


# 3. Sequencing, Repetition and Random number Generation

## 3.1 Sequencing

In [36]:
np.arange(1,21,dtype='int')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
np.arange(1,21,2,dtype='int')

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [40]:
np.arange(1,21,4,dtype='float')

array([ 1.,  5.,  9., 13., 17.])

In [42]:
np.linspace(start = 20,
    stop = 200,
    num=25) # creates equally spaced numbers from the start to end numbers specified

array([ 20. ,  27.5,  35. ,  42.5,  50. ,  57.5,  65. ,  72.5,  80. ,
        87.5,  95. , 102.5, 110. , 117.5, 125. , 132.5, 140. , 147.5,
       155. , 162.5, 170. , 177.5, 185. , 192.5, 200. ])

In [43]:
np.zeros_like(arr_3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [46]:
np.zeros((3,4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [47]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 3.2 Repetition

In [64]:
repeat_arr_2 = arr_2.repeat(repeats=20, axis=0)

In [65]:
repeat_arr_2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [67]:
repeat_arr_21 = arr_2.repeat(repeats=20)
repeat_arr_21

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

## 3.3 Creating random numbers

In [70]:
random_num = np.random.rand(10,5) # Create an array of the given shape and populate it with random samples from a uniform distribution
random_num

array([[0.16695179, 0.73514569, 0.26814635, 0.23987454, 0.26016013],
       [0.47935001, 0.02431929, 0.62260026, 0.01277919, 0.25350278],
       [0.68538068, 0.22132908, 0.30794639, 0.33844345, 0.49925292],
       [0.218789  , 0.11746539, 0.16960217, 0.93846502, 0.11558931],
       [0.87883144, 0.67145036, 0.52842939, 0.70573024, 0.24995998],
       [0.33996055, 0.30217552, 0.81391817, 0.05839237, 0.1845112 ],
       [0.60737536, 0.77567785, 0.18658758, 0.45887873, 0.77885513],
       [0.27705871, 0.43815778, 0.95588177, 0.06477701, 0.39234304],
       [0.52303505, 0.63440992, 0.27138767, 0.80192607, 0.95661017],
       [0.38958382, 0.42237333, 0.50902692, 0.14134857, 0.09286659]])

In [74]:
np.random.seed(10)
random_num_normal_distribution = np.random.randn(10,5) # Return a sample (or samples) from the "standard normal" distribution
random_num_normal_distribution

array([[ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597],
       [-0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737, -0.96506567,  1.02827408,  0.22863013],
       [ 0.44513761, -1.13660221,  0.13513688,  1.484537  , -1.07980489],
       [-1.97772828, -1.7433723 ,  0.26607016,  2.38496733,  1.12369125],
       [ 1.67262221,  0.09914922,  1.39799638, -0.27124799,  0.61320418],
       [-0.26731719, -0.54930901,  0.1327083 , -0.47614201,  1.30847308],
       [ 0.19501328,  0.40020999, -0.33763234,  1.25647226, -0.7319695 ],
       [ 0.66023155, -0.35087189, -0.93943336, -0.48933722, -0.80459114],
       [-0.21269764, -0.33914025,  0.31216994,  0.56515267, -0.14742026]])